// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 새 에이전트를 돌릴 백엔드 — ★오늘 받는 값은 `Claude` 하나뿐이다★.
 *
 * 코어에는 다른 백엔드도 있지만(`agent::backend` 의 codex·gemini·shell) **프로필 생성 경로가
 * 그것들로 도는지 확인된 바 없다** — 그래서 칸만 지금 열고 값은 좁혀 둔다(나중에 계약 **모양**이
 * 바뀌지 않게).
 * ★넓히는 것은 「변형 하나 더」가 아니라 **디스크 호환을 깨는 이주**다★: 여기 변형을 늘리려면
 * 실행 명령(`AgentCommand`)에 짝이 있어야 하는데 그 enum 은 `#[serde(tag = "kind")]` 로
 * **`agents.json` 에 그대로 적힌다**. 새 빌드가 새 kind 를 쓴 프로필을 저장하고 나면 옛 빌드는 그
 * 파일을 **한 덩이로** 파싱하다 실패해 `.corrupt` 로 밀어내고 **빈 명부로 뜬다** — 그 빌드에서
 * 에이전트가 전부 사라진다(persistence `FileProfileStore::load`). 넓힐 때 그 이주를 함께 설계할 것.
 */
export type AgentBackend = "Claude";
