// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { Capabilities } from "./Capabilities";

/**
 * epoch 는 재구독 트리거(`[agentId,epoch]`).
 */
export type AgentInfo = { id: string, 
/**
 * 표시용 이름(ProfileRegistry 단일 진실원, 없으면 id 앞 8자).
 */
name: string, cwd: string, status: AgentStatus, cols: number, rows: number, epoch: number, capabilities: Capabilities, };
