// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInfo } from "./AgentInfo";
import type { AgentProfile } from "./AgentProfile";
import type { AgentStatus } from "./AgentStatus";
import type { Capabilities } from "./Capabilities";
import type { OutputChunk } from "./OutputChunk";
import type { RequestId } from "./RequestId";
import type { RestoreReport } from "./RestoreReport";
import type { SnapshotChunk } from "./SnapshotChunk";
import type { SubscribeAction } from "./SubscribeAction";

/**
 * core→UI 이벤트 envelope(설계 §3, JSON 경로). TerminalBytes 출력은 여기 없음(binary frame).
 */
export type AgentEvent = { "Hello": { protocol_version: number, daemon_version: string, 
/**
 * 데몬 전체 capability(에이전트별 capability 는 AgentInfo 에).
 */
capabilities: Capabilities | null, } } | { "Ack": { request_id: RequestId, } } | { "SubscribeAck": { agent_id: string, action: SubscribeAction, current_epoch: number, oldest_seq: number, latest_seq: number, 
/**
 * 이 seq+1 부터 replay 를 보낸다(클라가 dedup 기준).
 */
replay_from: number, 
/**
 * ring 밖으로 밀려 일부 손실(clear+tail). UI "output truncated" 표시.
 */
truncated: boolean, } } | { "Output": { agent_id: string, epoch: number, seq: number, chunk: OutputChunk, } } | { "ReplayComplete": { agent_id: string, epoch: number, } } | { "StatusChanged": { agent_id: string, status: AgentStatus, epoch: number, } } | { "AgentListUpdated": { agents: Array<AgentInfo>, } } | { "RestoreResult": { report: RestoreReport, } } | { "InputLeaseChanged": { agent_id: string, held: boolean, } } | { "ProfileListUpdated": { profiles: Array<AgentProfile>, } } | { "Snapshot": { agent_id: string, chunks: Array<SnapshotChunk>, } } | { "Created": { request_id: RequestId, profile: AgentProfile, } } | { "Spawned": { request_id: RequestId, agent: AgentInfo, } } | { "Error": { request_id: RequestId | null, message: string, } };
