// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentStatus = { "type": "Running" } | { "type": "Exiting" } | { "type": "Exited", code: number | null, } | { "type": "Failed", message: string, } | { "type": "Killed" };
