// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSpawnCommand } from "./AgentSpawnCommand";
import type { RestartPolicy } from "./RestartPolicy";

/**
 * 영속 프로필 wire 미러 — core `profile::AgentProfile` 의 직렬화 형태와 일치.
 * 프로필 CRUD command/event(ProfileListUpdated)에 실린다.
 */
export type AgentProfile = { id: string, name: string, command: AgentSpawnCommand, 
/**
 * 정규화된 cwd(PathBuf 의 JSON 표현 = 문자열).
 */
cwd: string, 
/**
 * ※자격증명 금지(평문 persist).
 */
env: Array<[string, string]>, 
/**
 * 현재 claude 세션 id(없으면 None).
 */
claude_session_id: string | null, 
/**
 * 폐기된 과거 세션 id 이력.
 */
old_session_ids: string[], epoch: number, auto_restore: boolean, restart_policy: RestartPolicy, created_at: bigint, last_active: bigint, last_restore: number | null, };
