// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "./RequestId";

/**
 * UI→core 요청 envelope(설계 §3). side-effect 명령은 `request_id` 로 idempotent.
 * (Profile CRUD 는 phase 1 에서 core profile 타입 합류 후 추가 — 지금은 보류.)
 */
export type AgentCommand = { "Spawn": { profile_id: string, request_id: RequestId, } } | { "Kill": { agent_id: string, request_id: RequestId, } } | { "Interrupt": { agent_id: string, request_id: RequestId, } } | { "WriteStdin": { agent_id: string, data: number[], request_id: RequestId, } } | { "Resize": { agent_id: string, cols: number, rows: number, viewport_id: string | null, } } | { "Subscribe": { agent_id: string, epoch: number | null, after_seq: number | null, } } | { "Unsubscribe": { agent_id: string, } } | "ListAgents" | { "StopDaemon": { force: boolean, kill_agents: boolean, request_id: RequestId, } };
