// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSpawnCommand } from "./AgentSpawnCommand";
import type { RestartPolicy } from "./RestartPolicy";

/**
 * 영속 프로필 wire 미러 — core `profile::AgentProfile` 의 직렬화 형태와 일치.
 * 프로필 CRUD command/event(ProfileListUpdated)에 실린다.
 */
export type AgentProfile = { id: string, name: string, command: AgentSpawnCommand, 
/**
 * 정규화된 cwd(PathBuf 의 JSON 표현 = 문자열).
 */
cwd: string, 
/**
 * ※자격증명 금지(평문 persist).
 */
env: Array<[string, string]>, 
/**
 * 현재 claude 세션 id(없으면 None).
 */
claude_session_id: string | null, 
/**
 * 폐기된 과거 세션 id 이력.
 */
old_session_ids: string[], epoch: number, auto_restore: boolean, 
/**
 * **예약(reserved)** — 동작 미구현, 제거 금지(RestartPolicy 주석 참조).
 */
restart_policy: RestartPolicy, 
/**
 * 크래시 가드 카운터(수동 재시작 시 0 리셋). **예약(reserved)** — 동작 미구현, ADR-0016 유효.
 */
restart_count: number, 
/**
 * Failed(자동복원 suspend) 사유 — 콜드부팅 넘어 영속, 수동 깨우기 전까지 자동복원 제외(ADR-0016).
 * **예약(reserved)** — 동작 미구현이나 ADR-0016에서 유효, 제거 금지(버전 bump 유발).
 */
failed_reason: string | null, created_at: bigint, last_active: bigint, 
/**
 * 마지막 프로세스 기동 시각(기록·디버깅용, 리셋 판정엔 미사용).
 */
last_start_at: number | null, };
