// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 에이전트 생명주기 상태 — internally-tagged(`type`). 프론트 discriminated union.
 * core(types.rs) AgentStatus 와 글자 그대로 일치.
 */
export type AgentStatus = { "type": "Running" } | { "type": "Exiting" } | { "type": "Exited", code: number | null, } | { "type": "Failed", message: string, } | { "type": "Killed" };
