// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * core `failure::AgentFailureKind` 와 동일. 「마지막 실패」의 종류 어휘 — **화면 문구는 여기
 * 없다**: 종류 → {다시 해볼 가치 · 문구 · 권하는 행동} 표는 프론트가 진다
 * (ADR-0172 결정 5 · ADR-0173).
 *
 * ★상태(`AgentStatus`)와 별개 축이라 합치지 않는다★ — "도는 중인데 마지막 실패를 든" 조합이
 *   표현돼야 화면의 「도는 중이 이긴다」 규칙이 성립한다.
 * ★변형을 늘리려면 `declare_failure_kinds!` 호출 한 곳만 고친다★ — 여기 직접 쓸 수 없다.
 */
export type AgentFailureKind = "NoConversationToResume" | "SpawnFailed" | "EarlyExitAfterResume" | "Other";
