// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 에이전트 실행 명령 wire 미러 — core `profile::AgentCommand` 와 동일(`#[serde(tag="kind")]`).
 */
export type AgentSpawnCommand = { "kind": "Claude", extra_args: Array<string>, } | { "kind": "Shell", program: string, args: Array<string>, };
