// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlCaps } from "./ControlCaps";
import type { InputCaps } from "./InputCaps";
import type { ModelCaps } from "./ModelCaps";
import type { OutputCaps } from "./OutputCaps";
import type { SessionCaps } from "./SessionCaps";

/**
 * 영역별 capability(bool 폭증 방지). 슬롯이 렌더러/UI 분기에 사용.
 */
export type Capabilities = { input: InputCaps, output: OutputCaps, control: ControlCaps, session: SessionCaps, model: ModelCaps, };
