// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * claude 출력 포맷 wire 미러 — core `profile::ClaudeOutputFormat` 와 동일(ADR-0044).
 * Terminal=PTY 대화형, StreamJson=헤드리스 NDJSON. 프론트 `src/api/types.ts` 와 글자 그대로 일치.
 */
export type ClaudeOutputFormat = "Terminal" | "StreamJson";
