// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal=PTY 대화형, StreamJson=헤드리스 NDJSON.
 */
export type ClaudeOutputFormat = "Terminal" | "StreamJson";
