// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 데몬 명부의 **클라이언트 투영** 한 줄([`AgentEvent::CommandList`] 의 원소).
 *
 * ★버스 계약이 아니라 wire 계약이라 여기 산다★ — 도구 crate 의 `CommandDecl`(등록 단위)과 필드가
 * 겹치지만 방향과 주인이 다르다: `CommandDecl` 은 주인→데몬이 얹는 것이고, 이쪽은 데몬이 명부를
 * 훑어 내려 주는 것이라 명부만 아는 칸(`available`)이 하나 더 붙는다.
 *
 * ★`available` 은 **지금 항상 `true`** 이고 분기 근거로 쓰지 말 것★ — 주인이 끊기면 그 이름이 명부에서
 * 사라져 목록에 아예 실리지 않으므로(ADR-0150 결정 3) 실려 온 항목은 전부 살아 있는 등록이다. `false` 는
 * 도달 불가고, 이 칸으로 가용성을 판정하는 코드는 **판정할 것이 없는 판정**이다. 칸을 떼지 않은 이유는
 * 떼는 것 자체가 wire 계약 변경인데 얻는 것이 없어서다(TRD §3-7).
 * `help` 는 주인이 얹은 문자열 **그대로**다(데몬이 열어보지 않으므로 가공도 없다).
 */
export type CommandListEntry = { name: string, help: string, available: boolean, };
