// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 데몬 명부의 **클라이언트 투영** 한 줄([`AgentEvent::CommandList`] 의 원소).
 *
 * ★버스 계약이 아니라 wire 계약이라 여기 산다★ — 도구 crate 의 `CommandDecl`(등록 단위)과 필드가
 * 겹치지만 방향과 주인이 다르다: `CommandDecl` 은 주인→데몬이 얹는 것이고, 이쪽은 데몬이 명부를
 * 훑어 내려 주는 것이라 명부만 아는 칸(`available`)이 하나 더 붙는다.
 *
 * `available=false` = **이름은 명부에 있으나 주인이 지금 없다**(연결이 끊긴 자취). 없는 이름과 갈라야
 * 호출자가 재시도할지를 정할 수 있어서 지우지 않고 남긴다 — 전자는 `OWNER_UNAVAILABLE`(나중에 다시),
 * 후자는 `UNKNOWN_COMMAND`(재시도 무의미)다(TRD §4-②). 만료는 없다 — 시간이 지나 자취가 사라지면
 * 같은 질문의 답이 시계에 따라 갈려 그 구분 자체가 무너진다(ADR-0141).
 * `help` 는 주인이 얹은 문자열 **그대로**다(데몬이 열어보지 않으므로 가공도 없다).
 */
export type CommandListEntry = { name: string, help: string, available: boolean, };
