// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlCaps = { resize: boolean, interrupt: boolean, cancel: boolean, graceful_shutdown: boolean, };
