// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`QueuedInputEvent::AckUnavailable`] 이 싣는 말풍선 사본.
 */
export type DeliveredCopy = { id: string, text: string, };
