// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`QueuedInputEvent::Dropped`] 의 원인 — wire 에서는 문자열 하나(`"Withdrawn"` 등).
 * ★`Unknown` 만 되살림 가능한 묘비를 남긴다★(뒤늦은 `Delivered` 가 이긴다).
 */
export type DropCause = "Withdrawn" | "Interrupted" | "AgentEnded" | "Rejected" | "Unknown";
