// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OutputCaps = { terminal_bytes: boolean, markdown: boolean, tool_events: boolean, usage: boolean, };
