// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Preset = { id: string, 
/**
 * 정규화된 cwd.
 */
cwd: string, 
/**
 * 사용자 지정 표시명 override(ADR-0061 리치화). `Some` → 그대로 표시, `None` → cwd basename 파생
 * (기존 동작 불변).
 */
name: string | null, };
