// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 영속 프리셋 wire 미러 — core `preset::Preset` 의 직렬화 형태와 일치(ADR-0061). 프리셋 CRUD
 * command/event(PresetList/PresetListUpdated)에 실린다. cwd 는 PathBuf 의 JSON 표현(문자열).
 * 이름은 저장하지 않고 프론트가 cwd basename 으로 파생한다(ADR-0061).
 */
export type Preset = { id: string, 
/**
 * 정규화된 cwd(PathBuf 의 JSON 표현 = 문자열).
 */
cwd: string, };
