// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeliveredCopy } from "./DeliveredCopy";
import type { DropCause } from "./DropCause";

/**
 * 대기 입력 명부 사건 — agent `QueuedInputEvent` 의 미러. 판별자 = `"kind"`(바깥 봉투의 `"type"` 과 겹치지
 * 않게 — [`TurnOutcome`] 과 같은 이유).
 *
 * ★`Delivered` 는 본문을 싣지 않는다★ — 말풍선 본문은 앞선 `Queued` 의 `text`(우리 로컬 사본)다.
 * ★`AckUnavailable.delivered` 는 링에 적힐 때 늘 채워져 있다(agent 코어가 채운다)★ — 그 사건이 받음으로
 *   닫는 항목마다 (id, 본문) 한 벌. 링 창이 `Queued` 를 잃은 창도 이 사본으로 그 자리 말풍선을 그린다.
 */
export type QueuedInputEvent = { "kind": "Queued", id: string, text: string, } | { "kind": "CancelRequested", id: string, } | { "kind": "CancelAnswered", id: string, removed: boolean, } | { "kind": "CancelFailed", id: string, } | { "kind": "Delivered", id: string, } | { "kind": "Dropped", id: string, cause: DropCause, } | { "kind": "AckUnavailable", delivered: Array<DeliveredCopy>, };
