// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 취소 대기 행의 두 칸 — 명부의 환원 상태 그대로다(스냅숏 위에 뒤 사건을 다시 환원하려면 둘 다 필요하다).
 * `answer` = `none`(우리 취소 요청의 응답이 아직 없다) | `not_removed`(안 뺐다고 답했거나 요청이 실패했다).
 * `vendor_closed` = 그 id 의 벤더 닫힘을 이미 봤다.
 */
export type QueuedInputCancel = { answer: string, vendor_closed: boolean, };
