// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestoreOutcome } from "./RestoreOutcome";

export type RestoreReport = { agent_id: string, epoch: number, outcome: RestoreOutcome, };
