// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestoreOutcome } from "./RestoreOutcome";

/**
 * 복원 시도 결과 통지(AgentEvent::RestoreResult 페이로드).
 */
export type RestoreReport = { agent_id: string, epoch: number, outcome: RestoreOutcome, };
