// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RestoreOutcome = { "type": "Resumed" } | { "type": "Started" } | { "type": "FreshFallback", old_sid: string | null, new_sid: string, reason: string, } | { "type": "Blocked", reason: string, } | { "type": "Failed", reason: string, };
