// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 자동 재시작 정책 wire 미러 — core `profile::RestartPolicy` 와 동일.
 */
export type RestartPolicy = "Never" | "OnCrash" | "Always";
