// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 출력 스냅샷 청크 wire 미러 — core `types::OutputChunk`({seq, data}) 와 일치.
 * GetSnapshot 응답(AgentEvent::Snapshot)에 실린다. JSON 경로라 data 는 number[].
 */
export type SnapshotChunk = { seq: number, data: number[], };
