// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * core `types::OutputChunk` 와 일치.
 */
export type SnapshotChunk = { seq: number, data: number[], };
