// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 구조화 출력 이벤트 wire 미러(ADR-0045 tag1 StructuredEvent) — core `OutputEvent`의 **충실한 미러**.
 *
 * ★왜 새 타입인가(OutputChunk 확장 아님)★: 기존 wire `OutputChunk`(아래)는 S14 잔재라 `turn_id`/
 * `id`/`message_id`가 없고 `MessageDone`/`Error` variant도 없다. 게다가 `AgentEvent::Output`·
 * `export_all_to` 사용처에 묶여 있어 확장하면 그 계약이 깨질 위험이 있다. ADR-0045 "self-describing +
 * 교체성(optional turn_id/message_id 보존)"을 만족하려면 core `OutputEvent`를 필드 유실 0으로 미러해야
 * 하므로, 오염 없는 **새 wire 타입**을 신설한다(OutputChunk 는 GetSnapshot 스냅샷 전용으로 그대로 둔다).
 *
 * ★core↔wire 변환은 daemon adapter★(ADR-0003 격리): core `OutputEvent`(도메인 타입, Serialize 미부착)
 * → 이 wire 타입은 daemon `connection_core::output_event_to_wire` 가 명시 매핑한다. protocol 은 wire
 * 타입만 소유(core 무의존).
 *
 * ★TerminalBytes 는 제외★: 콘솔 raw 바이트는 tag0 terminal frame(payload=raw bytes)으로만 흐르고 tag1
 * payload 에 실리지 않는다(codec.rs: tag0=TerminalBytes / tag1=StructuredEvent). 따라서 이 미러에는
 * TerminalBytes variant 를 두지 않는다 — core `OutputEvent::TerminalBytes` 가 이 변환에 오면 adapter 가
 * 방어적으로 흡수(근거 주석은 output_event_to_wire).
 *
 * ★self-describing serde★: internally-tagged(`#[serde(tag="type")]`) — payload JSON 에 `"type"` 판별자가
 * 박혀 프론트가 JSON.parse 후 variant 를 가른다(codec 은 이 스키마를 모른다 — opaque tag1 payload, ADR-0045).
 * wire 직렬화 형식 = JSON(serde_json) — daemon adapter 가 `serde_json::to_vec` 로 tag1 payload 를 만든다.
 */
export type StructuredEvent = { "type": "TextDelta", text: string, turn_id: string | null, message_id: string | null, } | { "type": "ToolCall", name: string, args_json: string, 
/**
 * 호출 식별자(권한 UX·결과 매칭용). claude tool_use id 등.
 */
id: string | null, turn_id: string | null, message_id: string | null, } | { "type": "Usage", input_tokens: number, output_tokens: number, turn_id: string | null, } | { "type": "MessageDone", turn_id: string | null, message_id: string | null, } | { "type": "Error", message: string, } | { "type": "Structured", kind: string, json: string, };
