// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Subscribe 결과 분기(설계 §1-3).
 */
export type SubscribeAction = "Reset" | "TruncatedReplay" | "Resume";
