// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 도구 호출의 중립 종류 — [`StructuredEvent::ToolCall`] 의 `category`(agent `ToolCategory` 미러). wire 에서는
 * 문자열 하나(`"Read"` 등).
 *
 * ★벤더 도구 이름 · item 타입은 여기 오지 않는다★(ADR-0004) — 판정은 각 backend 번역기 안에서 끝난다.
 * ★프론트 소비자는 모르는 낱말을 `Other` 로 읽는다★ — 더 새 데몬이 변형을 더해도 화면이 선다.
 */
export type ToolCategory = "Read" | "Search" | "List" | "Edit" | "Command" | "Web" | "Agent" | "Mcp" | "Other";
