// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 도구 호출 끝 결과의 중립 결말 — [`StructuredEvent::ToolResult`] 의 `outcome`(agent `ToolOutcome` 미러). wire
 * 에서는 문자열 하나(`"Failed"` 등).
 *
 * - `Completed` = 정상 완료. ★지금 어느 데몬도 싣지 않는다★ — 실패 · 거부만 오고 이 낱말은 선 어휘로만 있다.
 * - `Failed` = 돌다 실패했다.
 * - `Declined` = 실행되지 않았다 — 우리 거절로 귀속되지 않은 거부. 이유는 모른다.
 * - `Refused` = 대시보드가 승인 요청을 거절해 실행되지 않았다.
 *
 * ★벤더 끝 상태 문자열은 여기 오지 않는다★(ADR-0004). ★프론트 소비자는 모르는 낱말을 표식 없음으로 읽는다★ —
 * 더 새 데몬이 낱말을 더해도 화면이 선다.
 */
export type ToolOutcome = "Completed" | "Failed" | "Declined" | "Refused";
