// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 턴이 **어떻게** 끝났나 — [`StructuredEvent::TurnEnd`] 가 나르는 중립 어휘(agent `TurnOutcome` 미러).
 *
 * ★중립인 것은 **판별자**다 — `detail` 은 아니다★(ADR-0004): 상대 프로토콜의 상태 어휘
 *   (`completed`·`failed`·`inProgress` 같은 값)는 각 backend decoder 안에서 끝나고 밖으로는 이 네
 *   갈래만 나간다. 그래서 **소비자가 분기하는 축**에는 backend 이름이 없다.
 * ★그 대신 `detail` 에는 상대가 만든 문장이 그대로 실린다 — 그것이 이 칸의 계약이다★: 실패 사유는
 *   상대가 준 것이 유일한 정보이고(codex 는 `serverOverloaded` 같은 자기 라벨과 「다음 턴에 그대로
 *   넣을 문장」을 거기 싣는다), 중립 어휘로 옮기려면 뜻을 지어내야 한다. 그래서 이 칸의 등급은
 *   [`StructuredEvent::Error`] 의 `message` 와 **같다** — 사람이 읽는 불투명 문자열이고, 길이와
 *   자격증명 마스킹만 backend decoder 가 책임진다.
 * ★소비자 의무 = 그리기만 한다★: `detail` 을 파싱하거나 그 내용으로 분기하면 그 순간 프론트가
 *   backend 어휘를 알게 되고 격리가 실제로 샌다. 분기는 판별자로만 한다.
 * ★`Unknown` 을 아는 셋 중 하나로 접지 말 것★ — 접으려면 모르는 값의 뜻을 추측해야 하고, 틀리면
 *   화면이 거짓 결말을 그린다. 모른다는 사실 자체가 실린다.
 * ★self-describing serde★: internally-tagged(`#[serde(tag="kind")]`) — 바깥 봉투가 `"type"` 을 쓰므로
 *   여기는 `"kind"` 를 쓴다(같은 객체에 두 판별자가 겹치지 않게).
 */
export type TurnOutcome = { "kind": "Completed" } | { "kind": "Failed", detail: string | null, } | { "kind": "Interrupted" } | { "kind": "Unknown" };
