// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageWindow = { 
/**
 * **쓴** 양의 백분율 0–100(남은 양이 아니다). 생산자는 소수 넷째 자리로 반올림해 싣는다(agent
 * `usage/normalize.rs` 의 `PCT_SCALE`) — 받는 쪽은 남은 양을 보정 없이 `floor(100 − used_pct)` 로 보여 주므로,
 * 이진 부동소수 꼬리(0.55 × 100 = 55.00000000000001)가 정수 경계를 넘지 않는 것이 그 반올림에 기댄다.
 */
used_pct: number | null, 
/**
 * 리셋 시각, epoch 초.
 */
resets_at: number | null, 
/**
 * 이 값을 관측한 뒤 흐른 초.
 */
age_secs: number, 
/**
 * 데몬이 리셋 경과를 확인했다 — 한 번 서면 이 창에 새 값이 올 때까지 유지된다(벽시계가 되감겨도).
 */
expired: boolean, };
