// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 벤더 조회의 상태 코드.
 */
export type UsageVendorState = { "kind": "Ready" } | { "kind": "NotInstalled" } | { "kind": "NeedsLogin" } | { "kind": "Unavailable" } | { "kind": "Failed", next_attempt_in_secs: number | null, } | { "kind": "Rejected", retry_in_secs: number, };
