// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentBackendKind } from "./AgentBackendKind";
import type { UsageScopedWindow } from "./UsageScopedWindow";
import type { UsageServed } from "./UsageServed";
import type { UsageVendorState } from "./UsageVendorState";
import type { UsageWindow } from "./UsageWindow";

/**
 * 한 벤더·계정의 사용량 상태 — 데몬이 요청에 답할 때 싣는 한 장.
 *
 * ★시간 칸 규칙★: 절대 시각은 [`UsageWindow::resets_at`](서버가 준 epoch 초) 하나뿐이다. 나머지 시간
 *   칸(`age_secs`·`next_attempt_in_secs`·`retry_in_secs`)은 **이 답을 보낸 순간 기준 상대 초**라, 받는 쪽은
 *   받은 순간부터 흐른 만큼 더해 읽는다 — 양쪽 벽시계가 어긋나거나 되감겨도 흔들리지 않게.
 * ★표시 문구를 싣지 않는다★ — 상태는 코드 + 수만 나르고 문구는 받는 쪽이 번역 키로 만든다.
 * ★`null` 창·`null` 수는 「모른다」이지 0 이 아니다★ — 0% 로 그리면 안 된다.
 */
export type UsageLimitSnapshot = { vendor: AgentBackendKind, 
/**
 * 같은 벤더 안의 계정 — 지금은 늘 `"default"`(데몬 env 의 기본 로그인).
 */
account_key: string, five_hour: UsageWindow | null, weekly: UsageWindow | null, 
/**
 * 모델별 주간 창. 빈 배열 = 없음.
 */
model_scoped: Array<UsageScopedWindow>, plan: string | null, 
/**
 * 조회가 아직 진행 중이다 — 이 답의 값은 그 조회 전의 것이고, 결과는 다음 요청의 답에 실린다.
 */
in_flight: boolean, served: UsageServed, 
/**
 * `Ready` 가 아니어도 위 값들은 유효하다 — 실패는 마지막으로 알던 값을 지우지 않는다.
 * 예외는 `Unavailable` 이다 — 값을 싣지 않는다.
 */
state: UsageVendorState, };
