// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 비정상 상태의 원인.
 *
 * `kind` = 분류 낱말(예 `rate_limits_null`·`claude_error`·`rpc_error`·`limits_unavailable`·`timeout`).
 * ★enum 이 아니라 문자열이다★ — 분류가 늘어도 옛 셸이 스냅숏 전체를 못 읽는 일이 없게. 받는 쪽은
 *   번역하지 않고 그대로 보인다.
 * `code` = 상류가 준 수(Codex JSON-RPC `error.code`). `upstream` = 상류 원문 — 보내는 쪽이 이 순서로
 *   다듬은 것이다: 비밀 가림 → 공백류 제어(탭·개행·CR·VT·FF·NEL·U+2028/2029)는 공백, 그 밖의 제어·
 *   보이지 않는 서식 문자는 U+FFFD → 200자로 자름. 받는 쪽이 다시 정화할 필요는 없다.
 * ★`Debug` 는 `upstream` 을 글자 수로만 찍는다★ — 어디서 `{:?}` 로 찍혀도 원문이 로그에 안 나가게.
 *   원문은 wire(`Serialize`)와 비교(`PartialEq`)만 본다.
 */
export type UsageStateDetail = { kind: string, code: number | null, upstream: string | null, };
