// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageWindow } from "./UsageWindow";

/**
 * 모델별 주간 창 하나. `label` = 벤더가 준 표시용 이름.
 */
export type UsageScopedWindow = { label: string, window: UsageWindow, };
