// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageSourceKind } from "./UsageSourceKind";

export type UsageWindow = { 
/**
 * **쓴** 양의 백분율 0–100(남은 양이 아니다).
 */
used_pct: number | null, 
/**
 * 리셋 시각, epoch 초.
 */
resets_at: number | null, 
/**
 * 이 값을 관측한 뒤 흐른 초.
 */
age_secs: number, 
/**
 * 데몬이 리셋 경과를 확인했다 — 한 번 서면 이 창에 새 값이 올 때까지 유지된다(벽시계가 되감겨도).
 */
expired: boolean, source: UsageSourceKind, };
