// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 명부의 한 행.
 */
export type AgentRow = { id: string, name: string, state: string, cwd: string, parent?: string | null, };
