// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentSpawnOk = { agent_id: string, name: string, state: string, created: boolean, };
