// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentCancelQueuedInputArgs = { target: string, 
/**
 * ★필수다★ — 「없으면 가장 최근」 같은 기본값을 두지 않는다(TRD §5-6).
 */
input_id: string, };
