// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 새 에이전트를 돌릴 백엔드 — ★오늘 받는 값은 `Claude` 와 `Codex` 둘이다★(2026-09-22 에 codex 가
 * 들어왔다).
 *
 * 코어에는 다른 백엔드도 있지만(`agent::backend` 의 gemini·shell) **프로필 생성 경로가 그것들로
 * 도는지 확인된 바 없다** — 그래서 칸은 열어 두되 값은 확인된 둘로 좁혀 둔다(나중에 계약 **모양**이
 * 바뀌지 않게).
 * ★변형을 더하는 값어치는 **짝이 이미 있나**가 가른다★: 실행 명령(`AgentCommand`)은
 * `#[serde(tag = "kind")]` 로 **`agents.json` 에 그대로 적히고**, 모르는 kind 를 만난 옛 빌드는 그
 * 파일을 **한 덩이로** 파싱하다 실패해 `.corrupt` 로 밀어내고 **빈 명부로 뜬다**(persistence
 * `FileProfileStore::load`). 그러니 `AgentCommand` 에 **아직 없는** 백엔드를 여기 더하는 것은
 * 디스크 호환을 깨는 이주이고, 짝이 **이미 있는** 백엔드를 더하는 것은 이주가 아니다.
 * ★`Codex` 는 후자였다★ — `AgentCommand::Codex { extra_args, output_format }` 는 그 전부터 있었고
 * 사람 메뉴(`agentlist.createCodex`·`createCodexJson`)가 **그 모양 그대로** `agents.json` 에 이미
 * 쓰고 있었다. 이 문을 연 것은 새 kind 도 새 칸도 스키마 상향도 아니다 — ★한때 이 자리에 「codex 를
 * 여는 것은 디스크 호환을 깨는 이주다」라고 적혀 있었는데, 사람 문이 같은 모양을 이미 쓰고 있어
 * 그때도 사실이 아니었다.★
 * ★전자의 실물은 `Gemini` 다★ — `agent::backend::gemini` 는 stub 으로 서 있지만 `AgentCommand` 에
 * 짝이 없다. 그 낱말을 여기 더하는 편집은 **디스크에 새 kind 를 앉히므로** 위 이주를 함께 설계해야
 * 한다. 두 경우를 같은 무게로 읽지 말 것.
 * ★**왜** 열려 있고 **다음 낱말은 어떻게 여나**는 [`LLM_BACKEND_POLICY`] 가 진다★ — 그 표를 나머지
 * 생성 문들도 본다(그 표 머리말이 셋을 나눠 적는다).
 */
export type AgentBackend = "Claude" | "Codex";
