// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRow } from "./AgentRow";
import type { RosterStoreRow } from "./RosterStoreRow";

export type AgentListOk = { agents: Array<AgentRow>, store: RosterStoreRow, };
