// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentRenameOk = { agent_id: string, 
/**
 * 확정된 이름 — 요청한 이름과 다를 수 있다(명부 유일성 접미사).
 */
name: string, outcome: string, };
