// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentSpawnArgs = { 
/**
 * 깨울 대상(이름 또는 id). cwd 와 상호배타.
 */
target?: string | null, 
/**
 * 새로 만들어 띄울 작업 폴더. target 과 상호배타.
 */
cwd?: string | null, 
/**
 * 새로 만들 때만 쓴다 — 깨우기에는 적용되지 않는다.
 */
name?: string | null, };
