// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 새 에이전트의 출력 형식(= 렌더 모드) — 생성 시점에 고정되고 이후 불변이다(ADR-0044/0078).
 *
 * `Terminal` = PTY 대화형(xterm 렌더) · `StreamJson` = 헤드리스 NDJSON 스트림.
 * 어휘는 `ClaudeOutputFormat` 과 **변형도 wire 표기도** 같아야 한다 — 갈리면 프론트 allowlist
 * (`coerceOutputFormat`)와 이 입구가 같은 낱말을 다르게 읽는다. 그 일치를 산문이 아니라 컴파일러가
 * 지키는 자리는 `tests::the_declared_vocabularies_are_pinned_to_the_core_ones`.
 */
export type AgentOutputFormat = "Terminal" | "StreamJson";
