// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentMoveArgs = { target: string, 
/**
 * 새 부모(이름 또는 id). ★`null` = 최상위로 뗀다 · **필드 부재는 반려**★ — 오타 필드 하나가
 * 조용히 계층 해제로 실행되면 안 되므로 부재와 `null` 을 가른다(바깥 Option = 실렸나).
 */
parent: string | null | null, };
