// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueuedInputCancel } from "./QueuedInputCancel";

/**
 * 대기 목록의 한 줄.
 */
export type QueuedInputRow = { 
/**
 * 입력 id — `agent.cancelQueuedInput` 의 `input_id` 로 그대로 쓴다.
 */
id: string, text: string, 
/**
 * `queued` | `unconfirmed`(통로가 넘겼는데 받혔는지 모른다 — 우편이 그 결말을 기다린다) |
 * `cancelling`(취소 대기 — 결말이 날 때까지 목록에 남는다).
 */
state: string, 
/**
 * `cancelling` 행만 싣는다 — 그 밖은 `null`.
 */
cancel?: QueuedInputCancel | null, };
