// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoreStatusRow } from "./StoreStatusRow";

/**
 * 명부 저장소 둘 — `agents`(agents.json · 에이전트 명부) · `presets`(presets.json · 경로 북마크).
 */
export type RosterStoreRow = { agents: StoreStatusRow, presets: StoreStatusRow, };
