// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 저장소가 받지 않는 까닭 — `Newer`(이 데몬보다 새 판이 쓴 파일) | `Unreadable`(파일을 못 읽었다 — 잠김 ·
 * 권한 등).
 */
export type StoreRefusalWord = "Newer" | "Unreadable";
