// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoreRefusalWord } from "./StoreRefusalWord";
import type { StoreStateWord } from "./StoreStateWord";

/**
 * 저장소 파일 하나의 상태 행.
 */
export type StoreStatusRow = { state: StoreStateWord, 
/**
 * `ReadOnly` · `Refusing` 의 까닭 — `Writable` 이면 `null`.
 */
reason?: StoreRefusalWord | null, 
/**
 * `Newer` 일 때 그 파일이 적은 판 번호 — 그 밖은 `null`.
 */
file_version?: bigint | null, };
