// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 저장소 파일 하나의 상태 — `Writable`(쓸 수 있다) | `ReadOnly`(데몬이 뜰 때 그 파일을 받지 않았다 — 명부가
 * 비어 있고 이 실행 내내 바꾸는 요청은 전부 `CONFLICT` 다. 파일을 고치거나 바꾼 뒤 데몬을 다시 띄워야 풀린다) |
 * `Refusing`(마지막 저장이 거절됐다 — 다음 변경이 다시 판정하고, 받아들이면 풀린다. 그 사이 파일이 고쳐졌으면
 * 이 값은 낡았다).
 */
export type StoreStateWord = "Writable" | "ReadOnly" | "Refusing";
