// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentBackend } from "./AgentBackend";

export type UsageRefreshArgs = { 
/**
 * 어느 백엔드의 한도인가 — `agent.new` 와 같은 낱말.
 */
backend: AgentBackend, };
