// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentBackend } from "./AgentBackend";
import type { UsageServedWord } from "./UsageServedWord";
import type { UsageStateWord } from "./UsageStateWord";
import type { UsageWindowRow } from "./UsageWindowRow";

export type UsageRefreshOk = { backend: AgentBackend, account_key: string, plan?: string | null, windows: Array<UsageWindowRow>, in_flight: boolean, served: UsageServedWord, state: UsageStateWord, next_attempt_in_secs?: bigint | null, retry_in_secs?: bigint | null, detail_kind?: string | null, detail_code?: string | null, upstream?: string | null, };
