// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentBackend } from "./AgentBackend";
import type { UsageServedWord } from "./UsageServedWord";
import type { UsageStateWord } from "./UsageStateWord";
import type { UsageWindowRow } from "./UsageWindowRow";

export type UsageVendorRow = { backend: AgentBackend, 
/**
 * 같은 백엔드 안의 계정 — 지금은 늘 `"default"`(데몬의 기본 로그인).
 */
account_key: string, plan?: string | null, 
/**
 * 값이 있는 창만 — 5시간 · 주간 · 모델별 주간 차례.
 */
windows: Array<UsageWindowRow>, 
/**
 * 조회가 아직 진행 중이다 — 이 행의 값은 그 조회 전의 것이다.
 */
in_flight: boolean, served: UsageServedWord, state: UsageStateWord, 
/**
 * `Failed` 만 싣는다 — 다음 자동 조회까지 남은 초(이미 지났으면 0).
 */
next_attempt_in_secs?: bigint | null, 
/**
 * `Rejected` 만 싣는다 — 이 초가 지나기 전엔 강제 새로고침도 조회를 내보내지 않는다.
 */
retry_in_secs?: bigint | null, 
/**
 * 비정상 상태의 분류 낱말(예 `timeout`·`rpc_error`) — 번역하지 않는 문자열이다. `null` = 원인을 모른다.
 */
detail_kind?: string | null, 
/**
 * 상류가 준 수(Codex JSON-RPC `error.code`)의 10진 문자열.
 *
 * ★수가 아니라 문자열인 것은 결정이다★ — 선언 매크로가 칸 속성을 옮기지 못해 `i64` 를 실으면 TS 가
 *   `bigint` 가 된다(ts-rs 기본). wire 의 같은 칸은 `number | null` 이다(protocol `UsageStateDetail.code`).
 */
detail_code?: string | null, 
/**
 * 상류 원문(비밀 가림 · 공백류 제어는 공백 · 200자) — UI 와 이 행에만 가고 로그에는 안 간다.
 *
 * ★이 타입의 `Debug` 는 매크로가 derive 해 원문을 그대로 싣는다★ — `{:?}` 로 로그에 찍지 말 것. 마감 뒤
 *   결과 로그는 JSON 사본에서 이 이름의 키를 걷어 낸다(daemon `command_delivery::log_late_local`).
 */
upstream?: string | null, };
