// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 답이 이 요청이 기다린 조회에서 나왔나 — 데몬 `usage_service::UsageServed` 를 그대로 옮긴 단어.
 */
export type UsageServedWord = "Fresh" | "Cached";
