// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 사용량 창의 종류 — `FiveHour`(5시간) · `Weekly`(주간) · `ModelWeekly`(모델별 주간 — `label` 이 그 이름).
 */
export type UsageWindowWord = "FiveHour" | "Weekly" | "ModelWeekly";
