// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 벤더 조회의 상태 — wire `UsageVendorState` 여섯과 1:1 이다(칸은 [`UsageVendorRow`] 가 편다).
 */
export type UsageStateWord = "Ready" | "NotInstalled" | "NeedsLogin" | "Unavailable" | "Failed" | "Rejected";
