// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageWindowWord } from "./UsageWindowWord";

/**
 * 사용량 한도 창 하나.
 */
export type UsageWindowRow = { window: UsageWindowWord, 
/**
 * `ModelWeekly` 만 싣는다(벤더가 준 표시용 이름) — 나머지는 `null`.
 */
label?: string | null, 
/**
 * **쓴** 양의 백분율 0–100(남은 양이 아니다). `null` = 모른다 — 0 이 아니다.
 */
used_pct?: number | null, 
/**
 * 남은 양 — 화면과 같은 `floor(clamp(100 − used_pct, 0, 100))`. `used_pct` 가 `null` 이면 `null`.
 */
left_pct?: bigint | null, 
/**
 * 리셋 시각, epoch 초 — 이 행의 유일한 절대 시각이다.
 */
resets_at?: bigint | null, 
/**
 * 이 값을 관측한 뒤 흐른 초(답한 순간 기준).
 */
age_secs: bigint, 
/**
 * 데몬이 리셋 경과를 확인했다 — 값은 지난 창의 것이다.
 */
expired: boolean, };
