// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `restore_answer` · `restore.answer` 의 답(TRD §6-7).
 */
export type AnswerReply = { 
/**
 * 사본 화면으로 다시 그린 레이아웃 창 수 — main + 모델에 남은 새 팝아웃(화면을 바꾸기 전에 닫힌 창은 빠진다).
 * 트리 창은 세지 않는다(자리만 입힌다 — [`RestoreStatusView::windows`] 와 같은 셈) · 거절은 `0`.
 */
restored_windows: number, 
/**
 * 마감 안에 그 답을 실은 `state.json` 이 발행됐다. `false` = 마감 안에 디스크에 붙었다고 확인하지 못했다 —
 * 다음 부팅이 다시 물을 수 있다. 기록기가 없으면(가드) 반드시 다시 묻고, 쓰기 실패 · 마감 초과면 기록기가 그
 * 해시를 쥔 채 뒤 쓰기에서 붙일 수도 있다(`saver` 머리 「해결 칸」).
 */
durable: boolean, };
