// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `restore.status` 의 `crash_copy` 칸이자 [`EVT_RESTORE_CHANGED`] 의 실을 것(TRD §6-7) — wire 철자는 `"none"` ·
 * `"awaiting"` · `"answered"`.
 *
 * - `None` = 이 실행에서 물을 사본이 없다 — 이 판이 적용하지 못하는 사본(버전 초과 — N6)이 디스크에 있어도
 *   이 값이다.
 * - `Awaiting` = 답하지 않은 사본이 있다 — 사람 UI 는 답할 때까지 main 을 막는다.
 * - `Answered` = 이 실행에서 답했다 — 사본 파일은 기록기가 지울 때까지 디스크에 남아 있을 수 있다(I2).
 */
export type CrashCopyStatus = "none" | "awaiting" | "answered";
