// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 칸 틀 안쪽 여백(CSS px, 소수 허용 — 배율에 따라 테두리 폭이 소수로 잴 수 있다).
 */
export type Insets = { t: number, r: number, b: number, l: number, };
