// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotContent } from "./SlotContent";
import type { SplitDir } from "./SplitDir";

export type LayoutNode = { "type": "slot", id: string, content: SlotContent, } | { "type": "split", 
/**
 * 이 split 노드의 정체 — 분할마다 새로 뽑고, 노드가 자리를 옮겨도(형제 승격) 따라간다. 프론트는
 * 렌더러 인스턴스를 이 값으로 가른다(`ViewLayoutRenderer`).
 */
id: string, dir: SplitDir, ratio: number, a: LayoutNode, b: LayoutNode, };
