// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 한 슬롯의 방향별 이웃(각 = 인접 slot id 또는 None). 논리 도면 파생(픽셀 무관). ADR-0068.
 */
export type Neighbors = { up: string | null, down: string | null, left: string | null, right: string | null, };
