// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingItem } from "./SettingItem";

export type ResetOutcome = { rev: number, 
/**
 * 선택자가 덮은 키 전부(표 순서) — 호출 뒤 모두 기본값이다.
 */
reset: Array<string>, 
/**
 * 그중 유효 값이 실제로 바뀐 키의 새 값(= 기본값). 비었으면 알림도 `rev` 도 없다 — 파일은 바로잡았을 수
 * 있다([`SettingsService::reset`]).
 */
changed: Array<SettingItem>, };
