// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrashCopyStatus } from "./CrashCopyStatus";

/**
 * `restore_status` · `restore.status` 의 답. 뒤 셋은 `Awaiting` 일 때만 값이고 그 밖은 `null` 이다(사본의 값).
 */
export type RestoreStatusView = { crash_copy: CrashCopyStatus, 
/**
 * 사본을 적은 시각 — 유닉스 밀리초.
 */
saved_at_ms: number | null, 
/**
 * 사본의 레이아웃 창 수 — main + 팝아웃. 트리 창은 세지 않는다(탭이 없고 수락이 자리만 입힌다 —
 * [`AnswerReply::restored_windows`] 와 같은 셈).
 */
windows: number | null, 
/**
 * 사본의 모든 창의 탭 수 합.
 */
tabs: number | null, };
