// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrashCopyStatus } from "./CrashCopyStatus";
import type { StateFileStatus } from "./StateFileStatus";

/**
 * `restore_status` · `restore.status` 의 답. `saved_at_ms` · `windows` · `tabs` · `durable` 은 `Awaiting` 일 때만
 * 값이고 그 밖은 `null` 이다(사본의 값). `state_file` 은 늘 값이다.
 */
export type RestoreStatusView = { crash_copy: CrashCopyStatus, 
/**
 * 사본을 적은 시각 — 유닉스 밀리초.
 */
saved_at_ms: number | null, 
/**
 * 사본의 레이아웃 창 수 — main + 팝아웃. 트리 창은 세지 않는다(탭이 없고 수락이 자리만 입힌다 —
 * [`AnswerReply::restored_windows`] 와 같은 셈).
 */
windows: number | null, 
/**
 * 사본의 모든 창의 탭 수 합.
 */
tabs: number | null, 
/**
 * 이 실행이 화면 상태를 저장하나(부팅이 가드가 아니었다) — `true` = 답(수락 · 거절)을 디스크에 붙이고 사본을
 * 지운다. `false` = 이 실행은 아무것도 저장하지 않는다(가드 ⅰ · ⅱ) — 답해도 크래시 때 화면이 디스크에 남아(사본
 * 또는 정상 종료 표시 없는 `state.json`) 다음 부팅이 다시 묻는다. 그 답이 실제로 디스크에 붙었는지는
 * [`AnswerReply::durable`] 이 말한다.
 */
durable: boolean | null, state_file: StateFileStatus, };
