// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SchemaItem = { key: string, 
/**
 * `"choice"` · `"css-length"` · `"css-number"`.
 */
kind: string, default: string, 
/**
 * `choice` 만 — 정규 철자.
 */
choices: Array<string> | null, 
/**
 * 양 끝 포함 · 정규형. `css-length` 는 받는 단위마다 한 값씩 `, ` 로 잇는다(`"8px, 0.5rem, 0.5em"`).
 * `choice` 는 `None`.
 */
min: string | null, 
/**
 * [`SchemaItem::min`] 과 같은 모양.
 */
max: string | null, description: string, };
