// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetOutcome = { 
/**
 * `changed: false` 면 호출 전과 같은 값.
 */
rev: number, key: string, 
/**
 * 정규형.
 */
value: string, 
/**
 * `false` = 유효 값이 이미 그 값이었다 — 알림도 `rev` 도 없다. 파일은 바로잡았을 수 있다
 * ([`SettingsService::set`]).
 */
changed: boolean, };
