// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingItem = { key: string, 
/**
 * 정규형. 덮어쓴 값이 없으면 기본값.
 */
value: string, 
/**
 * 덮어쓴 값이 없다. 파일의 못 쓸 값이 기본값으로 접힌 키도 `true` 다.
 */
is_default: boolean, };
