// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaItem } from "./SchemaItem";

/**
 * `settings_schema` 의 답 — 버스 `settings.schema` 와 같은 모양(TRD §5-4).
 */
export type SettingsSchema = { 
/**
 * 표 순서.
 */
items: Array<SchemaItem>, };
