// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 슬롯 점유자 = 타입드 유니온(ADR-0060). 슬롯이 "무엇을 담는가"의 종류를 나타낸다.
 *
 * `LayoutNode` 와 **동일한 내부태깅**(`#[serde(tag="type")]` + snake_case)이라 ts-rs 가 프론트
 * discriminated union(`{type:"empty"}` / `{type:"agent",agent_id:"…"}`)으로 생성한다. 후속 콘텐츠
 * 종류(FileTree/ControlPanel)는 variant 추가로 확장하고, 사용자 커스텀(프리셋 버튼셋)은 새 variant 가
 * 아니라 variant 내부 config 데이터로 표현한다(enum 폭발 방지 — ADR-0060 핵심 통찰).
 *
 * ★불변식(ADR-0060)★: `Agent` variant 는 데몬 에이전트의 **바인딩(agent_id 참조 문자열)만** 담는다 —
 * 라이브 출력 스트림은 여기 담지 않고 `OutputRouter` 가 agent_id 로 별도 라우팅한다(ADR-0041/0042/0046).
 * epoch(재spawn 재구독 트리거)도 레이아웃 트리 밖(agentStore 소유 — ADR-0007/0046). 즉 이 타입은
 * "슬롯이 어떤 에이전트에 묶였나"라는 정적 바인딩만 표현하고, 수명·스트림은 직교 축이 다룬다.
 */
export type SlotContent = { "type": "empty" } | { "type": "agent", agent_id: string, };
