// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 한 칸의 사각형 — 뷰 기준 정규화 [0,1] 경계 꼴(`x0 <= x1`, `y0 <= y1`).
 * 이웃 칸과 맞닿는 경계 값은 비트 단위로 같다(`src-tauri/src/layout/geometry.rs` 모듈 헤더 불변식).
 */
export type SlotRect = { slot_id: string, x0: number, y0: number, x1: number, y1: number, };
