// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitDir } from "./SplitDir";

/**
 * 한 분할 노드 — 이 분할 자신의 상자(두 자식을 합친 영역, 뷰 기준 정규화 [0,1] 경계 꼴) + 경계 좌표 `at`.
 * `at` 은 `dir` 이 `left_right` 면 x 축 값(a = 왼쪽), `top_bottom` 이면 y 축 값(a = 위)이다.
 */
export type SplitRect = { split_id: string, dir: SplitDir, x0: number, y0: number, x1: number, y1: number, at: number, };
