// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 분할 방향. Horizontal = 좌우(│로 가름), Vertical = 상하(─로 가름).
 */
export type SplitDir = "horizontal" | "vertical";
