// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 비율 쓰기(`set_split_ratio`)의 결말.
 *
 * - `Applied`: 값을 바꿨다 — version 이 올랐고 그 뷰의 레이아웃 스냅샷이 통지된다.
 * - `Unchanged`: 클램프한 값이 지금 값과 같다 — 무변경·무통지.
 * - `TooSmall`: 손대지 않았다 — 무변경·무통지. 사유는 둘이다 — 분할 상자가 두 쪽 모두 `min_pane_px`
 *   이상을 줄 만큼 크지 않다(px 범위가 비었다), 또는 그 값을 쓰면 어떤 칸의 폭·높이가 0 이 된다.
 *
 * 명령 버스 `split.setRatio` 의 `outcome` 과 철자가 같다.
 */
export type SplitRatioOutcome = "Applied" | "Unchanged" | "TooSmall";
