// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `restore.status` 의 `state_file` 칸(TRD §6-5) — 이 실행의 부팅이 `state.json` 을 어떻게 읽었나. 부팅 단계 ⑥ 이
 * 정하고 그 실행 내내 바뀌지 않으며, 크래시 사본과 무관하게 늘 값이다. wire 철자는 `"ok"` · `"unreadable"` ·
 * `"newer"` · `"corrupt_copied_aside"` · `"corrupt_not_copied"`.
 *
 * - `Ok` = 읽었거나 파일이 없었다. 사본을 못 떠 이 실행이 저장하지 않는 경우(가드 ⅱ)도 이 값이다 — 이 칸은
 *   `state.json` 읽기만 싣는다. 이 실행이 저장하나는 이 칸이 아니라 [`RestoreStatusView::saves`] 가 말한다.
 * - `Unreadable` = 읽기 자체가 실패했다(잠김 재시도 뒤 · 권한 — 가드 ⅰ). 파일은 그대로 두고, 이 실행은 화면 상태를
 *   하나도 저장하지 않으며, 다음 부팅이 다시 판정한다.
 * - `Newer` = 이 셸보다 새 판이 쓴 파일이라 기본 화면으로 시작했다(가드 ⅰ 과 같은 칸). 떠 두지도 덮지도 않고, 이
 *   실행은 화면 상태를 하나도 저장하지 않으며, 다음 부팅이 다시 판정한다.
 * - `CorruptCopiedAside` = 못 쓰는 파일(손상 · 상한 초과 · UTF-8 아님)이라 `state.json.corrupt` 로 떠 두고 기본
 *   화면으로 시작했다.
 * - `CorruptNotCopied` = 못 쓰는 파일(손상 · 상한 초과 · UTF-8 아님)인데 떠 두지 못한 채 기본 화면으로 시작했다 —
 *   원본은 백업 없이 덮인다(D8). 이미 있는 `state.json.corrupt` 는 앞선 시작이 떠 둔 것이지 이번 원본의 백업이
 *   아니다.
 */
export type StateFileStatus = "ok" | "unreadable" | "newer" | "corrupt_copied_aside" | "corrupt_not_copied";
