// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutNode } from "./LayoutNode";

/**
 * 한 View(탭/팝업 하나) = 레이아웃 트리 + 포커스 슬롯.
 */
export type View = { id: string, name: string, layout: LayoutNode, 
/**
 * 현재 포커스된 슬롯. 가리키던 슬롯이 사라지면 트리 첫 슬롯으로 폴백(없으면 None).
 */
focused_slot_id: string | null, };
