// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutNode } from "./LayoutNode";

/**
 * `get_view` 응답 + `layout:updated` 페이로드. version = 팝업 pull↔listen race 용(get_view race).
 */
export type ViewSnapshot = { view_id: string, layout: LayoutNode, focused_slot_id: string | null, 
/**
 * 변경마다 +1(ViewManager.version). 팝업이 pull 한 version 이하 emit 은 폐기(초기 유실·중복 방지).
 * ts-rs u64 기본 매핑=bigint 이나 serde_json 은 number 로 직렬화(런타임=JS number) → 타입도 number 로 고정
 * (불일치 시 프론트 race 가드 `snap.version > pulled` 에서 bigint↔number 혼용 에러, FIX-1). 카운터라 2^53 비현실적.
 */
version: number, };
