// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutNode } from "./LayoutNode";
import type { SlotSpatial } from "./SlotSpatial";

/**
 * `get_view` 응답 + `layout:updated` 페이로드. version = 팝업 pull↔listen race 용(get_view race).
 */
export type ViewSnapshot = { view_id: string, layout: LayoutNode, focused_slot_id: string | null,
/**
 * ★슬롯 공간 타깃 파생(ADR-0068)★: 각 말단 슬롯의 방향 이웃(up/down/left/right) + 읽기 순서(ordinal).
 * 논리 도면(split 방향·ratio)에서 산출한다 — 픽셀·getBoundingClientRect 무관(백엔드 권위 ADR-0035).
 * ordinal 순(위 먼저·왼쪽 먼저)으로 담긴다. 좌표 자체는 노출 안 함(ADR-0068 결정 3 — 좌표 보류).
 * 프론트는 이걸 그대로 받아 "우하단"·"이 슬롯 오른쪽" 같은 공간 지시를 slot id 로 옮긴다.
 */
slot_spatial: Array<SlotSpatial>,
/**
 * 변경마다 +1(ViewManager.version). 팝업이 pull 한 version 이하 emit 은 폐기(초기 유실·중복 방지).
 * ts-rs u64 기본 매핑=bigint 이나 serde_json 은 number 로 직렬화(런타임=JS number) → 타입도 number 로 고정
 * (불일치 시 프론트 race 가드 `snap.version > pulled` 에서 bigint↔number 혼용 에러, FIX-1). 카운터라 2^53 비현실적.
 */
version: number, };
