// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 탭 바용 View 메타(레이아웃 본체 제외 — `view:list-updated` 페이로드).
 */
export type ViewMeta = { id: string, name: string, };
